{% set name = "classy_vision" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # NOTE: the PyPI dist doesn't package the LICENSE in 0.2.0, use PyPI for future versions
  url: https://github.com/facebookresearch/ClassyVision/archive/v{{ version }}.tar.gz
  sha256: a6248472d172c3fce986bc1a3a5eeb3f5650c97c84516dde313993024f82a86d

build:
  number: 1
  skip: True  # [py<36 or not linux64]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pytorch >=1.4
    - torchvision >=0.5

test:
  imports:
    - classy_vision
    - classy_vision.dataset
    - classy_vision.heads
    - classy_vision.hooks
    - classy_vision.losses
    - classy_vision.meters
    - classy_vision.models
    - classy_vision.optim
    - classy_vision.tasks
    - classy_vision.trainer
  commands:
    - classy-project test_project

about:
  home: https://classyvision.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "An end-to-end PyTorch framework for image and video classification"
  doc_url: https://classyvision.ai/
  dev_url: https://github.com/facebookresearch/ClassyVision/

extra:
  recipe-maintainers:
    - mannatsingh
    - vreis
