{% set name = "classy_vision" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 469b0f1c4f55e2b6a0c1338cc4e357bb87eadedf22b63b05adb2ee61106f6aa8

build:
  number: 2
  skip: true  # [py<36 or not linux64 or py>37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pytorch >=1.3.1
    - torchvision >=0.4.2
    # NOTE: pillow can be removed once the torchvision version is upped
    - pillow ==6.2.1

test:
  imports:
    - classy_vision
  commands:
    - classy-project test_project

about:
  home: https://classyvision.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An end-to-end PyTorch framework for image and video classification
  doc_url: https://classyvision.ai/
  dev_url: https://github.com/facebookresearch/ClassyVision/

extra:
  recipe-maintainers:
    - mannatsingh
    - vreis
    - aadcock
