{% set name = "classy_vision" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # NOTE: the PyPI dist doesn't package the LICENSE in 0.2.0, use PyPI for future versions
  url: https://github.com/facebookresearch/ClassyVision/archive/v{{ version }}.tar.gz
  sha256: 2c1cf766fda5358396ebe213841e66b3f085743dc06d0b675249e54ba11465ca

build:
  number: 0
  skip: true  # [py<36 or not linux64]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
  host:
    - python
    - pip
  run:
    - python
    - pytorch >=1.3.1
    - torchvision >=0.4.2
    # NOTE: pillow can be removed once the torchvision version is upped
    - pillow ==6.2.1

test:
  imports:
    - classy_vision
    - classy_vision.dataset
    - classy_vision.heads
    - classy_vision.hooks
    - classy_vision.losses
    - classy_vision.meters
    - classy_vision.models
    - classy_vision.optim
    - classy_vision.tasks
    - classy_vision.trainer
  commands:
    - classy-project test_project

about:
  home: https://classyvision.ai
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An end-to-end PyTorch framework for image and video classification
  doc_url: https://classyvision.ai/
  dev_url: https://github.com/facebookresearch/ClassyVision/

extra:
  recipe-maintainers:
    - mannatsingh
    - vreis
